import "server-only";
import { createHash } from "node:crypto";
import type { DatabaseClient } from "../database/database";
import { getDatabaseClient } from "../database/database";
import type { AuthorizationPrincipal } from "../authorization/authorization-context-domain";
import { deriveTrustedTenantScope, type TenantPermissionPrincipal } from "../authorization/tenant-scoped-resource-domain";
import { bindTrustedAuditActor } from "../audit/audit-domain";
import { DatabaseAuditRepository } from "../audit/audit-repository";
import { createIdentifier } from "../auth/auth-domain";
import { authorizeSecureFileAccessCore, readSecureFileAccessCore, type SecureFileAccessLookup } from "../secure-files/secure-file-access-core";
import { createLocalTestPrivateObjectStorage } from "../secure-files/private-object-storage";
import { getServerEnvironment } from "../config/server-environment";
import type { SecureFileRecord } from "../secure-files/secure-file-domain";
import { EvidenceReviewAccessError,EvidenceReviewConflictError,EvidenceReviewInputError,assertVerifierPrincipal,createReviewConflictId,createReviewDecisionId,createReviewTaskId,createSupervisorObservationId,normalizeOutcome,normalizeReason,type EvidenceReviewKind,type EvidenceReviewOutcome,type EvidenceReviewTask } from "./evidence-review-domain";

type TaskRow={task_id:string;tenant_id:string;case_id:string;worker_account_id:string;evidence_kind:EvidenceReviewKind;source_record_id:string;source_version_id:string;secure_file_id:string|null;evidence_label:string;task_status:EvidenceReviewTask["taskStatus"];assigned_verifier_account_id:string|null;claimed_at:string|Date|null;decided_at:string|Date|null;created_at:string|Date;updated_at:string|Date};
type DelegatedSecureFileRow={file_sequence:number|string;file_id:string;schema_version:number|string;reservation_key:string;owner_account_id:string;owner_role:SecureFileRecord["ownerRole"];tenant_id:string|null;membership_id:string|null;storage_adapter_key:SecureFileRecord["storageAdapterKey"];object_key:string;display_filename:string;lifecycle_status:SecureFileRecord["lifecycleStatus"];file_extension:SecureFileRecord["fileExtension"];declared_mime:SecureFileRecord["declaredMime"];detected_mime:SecureFileRecord["detectedMime"];byte_size:number|string|null;content_sha256:string|null;quarantined_at:string|Date|null;available_at:string|Date|null;unsafe_at:string|Date|null;created_at:string|Date;updated_at:string|Date};
const iso=(v:string|Date)=>v instanceof Date?v.toISOString():new Date(v).toISOString(); const maybe=(v:string|Date|null)=>v===null?null:iso(v);
function task(row:TaskRow):EvidenceReviewTask{return Object.freeze({taskId:row.task_id,tenantId:row.tenant_id,caseId:row.case_id,workerAccountId:row.worker_account_id,evidenceKind:row.evidence_kind,sourceRecordId:row.source_record_id,sourceVersionId:row.source_version_id,secureFileId:row.secure_file_id,evidenceLabel:row.evidence_label,taskStatus:row.task_status,assignedVerifierAccountId:row.assigned_verifier_account_id,claimedAt:maybe(row.claimed_at),decidedAt:maybe(row.decided_at),createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)});}
const TASK_COLS="task_id,tenant_id,case_id,worker_account_id,evidence_kind,source_record_id,source_version_id,secure_file_id,evidence_label,task_status,assigned_verifier_account_id,claimed_at,decided_at,created_at,updated_at";
async function liveVerifier(db:DatabaseClient,p:AuthorizationPrincipal){assertVerifierPrincipal(p);const r=await db.query(`SELECT 1 FROM auth_sessions s JOIN auth_accounts a ON a.account_id=s.account_id JOIN auth_account_roles r ON r.account_id=a.account_id AND r.role='verifier' WHERE s.session_id=$1 AND s.account_id=$2 AND s.active_role='verifier' AND s.revoked_at IS NULL AND s.expires_at>CURRENT_TIMESTAMP AND a.account_status='active' FOR UPDATE OF s,a`,[p.sessionId,p.accountId]);if(!r.rows[0])throw new EvidenceReviewAccessError();}
async function audit(db:DatabaseClient,p:AuthorizationPrincipal,caseId:string,metadata:Record<string,unknown>){await new DatabaseAuditRepository(Promise.resolve(db)).append(bindTrustedAuditActor(p),{action:"assurance_case.status.changed",outcome:"succeeded",target:{type:"resource",reference:caseId},metadata});}
function sha(v:string){return createHash("sha256").update(v).digest("hex");}

export class EvidenceReviewService{
 constructor(private readonly database:DatabaseClient){}
 async listQueue(principal:AuthorizationPrincipal):Promise<readonly EvidenceReviewTask[]>{assertVerifierPrincipal(principal);const r=await this.database.query<TaskRow>(`SELECT ${TASK_COLS} FROM evidence_review_tasks WHERE task_status='QUEUED' OR assigned_verifier_account_id=$1 ORDER BY CASE task_status WHEN 'ASSIGNED' THEN 0 ELSE 1 END,created_at,task_id LIMIT 250`,[principal.accountId]);return Object.freeze(r.rows.map(task));}
 async findTask(principal:AuthorizationPrincipal,taskId:string):Promise<EvidenceReviewTask|null>{assertVerifierPrincipal(principal);const r=await this.database.query<TaskRow>(`SELECT ${TASK_COLS} FROM evidence_review_tasks WHERE task_id=$1 AND (task_status='QUEUED' OR assigned_verifier_account_id=$2)`,[taskId,principal.accountId]);return r.rows[0]?task(r.rows[0]):null;}
 async claim(principal:AuthorizationPrincipal,taskId:string,now=new Date()):Promise<EvidenceReviewTask>{return this.database.transaction(async db=>{await liveVerifier(db,principal);const conflict=await db.query(`SELECT 1 FROM evidence_review_conflicts WHERE task_id=$1 AND verifier_account_id=$2`,[taskId,principal.accountId]);if(conflict.rows[0])throw new EvidenceReviewConflictError("A declared conflict prevents this assignment.");const r=await db.query<TaskRow>(`UPDATE evidence_review_tasks SET task_status='ASSIGNED',assigned_verifier_account_id=$2,claimed_at=$3,updated_at=$3 WHERE task_id=$1 AND task_status='QUEUED' RETURNING ${TASK_COLS}`,[taskId,principal.accountId,now.toISOString()]);if(!r.rows[0])throw new EvidenceReviewConflictError("Task was already claimed or is unavailable.");return task(r.rows[0]);});}
 async declareConflict(principal:AuthorizationPrincipal,taskId:string,reason:string,now=new Date()):Promise<void>{const why=normalizeReason(reason);await this.database.transaction(async db=>{await liveVerifier(db,principal);const row=await db.query<TaskRow>(`SELECT ${TASK_COLS} FROM evidence_review_tasks WHERE task_id=$1 AND (task_status='QUEUED' OR assigned_verifier_account_id=$2) FOR UPDATE`,[taskId,principal.accountId]);if(!row.rows[0])throw new EvidenceReviewAccessError();await db.query(`INSERT INTO evidence_review_conflicts(conflict_id,task_id,verifier_account_id,reason,declared_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT(task_id,verifier_account_id) DO NOTHING`,[createReviewConflictId(),taskId,principal.accountId,why,now.toISOString()]);if(row.rows[0].assigned_verifier_account_id===principal.accountId&&row.rows[0].task_status==='ASSIGNED')await db.query(`UPDATE evidence_review_tasks SET task_status='QUEUED',assigned_verifier_account_id=NULL,claimed_at=NULL,updated_at=$2 WHERE task_id=$1`,[taskId,now.toISOString()]);});}
 async decide(principal:AuthorizationPrincipal,taskId:string,outcomeValue:unknown,reasonValue:unknown,now=new Date()):Promise<void>{const outcome=normalizeOutcome(outcomeValue),reason=normalizeReason(reasonValue);await this.database.transaction(async db=>{await liveVerifier(db,principal);const r=await db.query<TaskRow>(`SELECT ${TASK_COLS} FROM evidence_review_tasks WHERE task_id=$1 AND task_status='ASSIGNED' AND assigned_verifier_account_id=$2 FOR UPDATE`,[taskId,principal.accountId]);const row=r.rows[0];if(!row)throw new EvidenceReviewAccessError();const conflict=await db.query(`SELECT 1 FROM evidence_review_conflicts WHERE task_id=$1 AND verifier_account_id=$2`,[taskId,principal.accountId]);if(conflict.rows[0])throw new EvidenceReviewConflictError("Conflicted reviewer cannot decide this task.");if(!(await this.sourceIsCurrent(db,row)))throw new EvidenceReviewConflictError("Evidence version changed; this task is stale.");const inserted=await db.query(`INSERT INTO evidence_review_decisions(decision_id,task_id,source_version_id,verifier_account_id,outcome,reason,decided_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(task_id) DO NOTHING`,[createReviewDecisionId(),taskId,row.source_version_id,principal.accountId,outcome,reason,now.toISOString()]);if(inserted.affectedRows!==1)throw new EvidenceReviewConflictError("Evidence task already has a decision.");await db.query(`UPDATE evidence_review_tasks SET task_status=$3,decided_at=$4,updated_at=$4 WHERE task_id=$1 AND assigned_verifier_account_id=$2`,[taskId,principal.accountId,outcome,now.toISOString()]);await this.advanceCase(db,row,outcome,now,principal);await audit(db,principal,row.case_id,{reviewOutcome:outcome,evidenceKind:row.evidence_kind,sourceFingerprint:sha(row.source_version_id)});});}
 private async sourceIsCurrent(db:DatabaseClient,row:TaskRow):Promise<boolean>{if(row.evidence_kind==='identity'){const r=await db.query(`SELECT 1 FROM worker_identity_versions v JOIN worker_identities i ON i.identity_id=v.identity_id WHERE v.identity_version_id=$1 AND i.worker_account_id=$2 AND v.version_status='submitted' AND v.version_number=i.current_version_number`,[row.source_version_id,row.worker_account_id]);return Boolean(r.rows[0]);}if(row.evidence_kind==='supervisor_observation'){const r=await db.query(`SELECT 1 FROM supervisor_observations WHERE observation_id=$1 AND case_id=$2 AND worker_account_id=$3 AND observation_status='submitted'`,[row.source_version_id,row.case_id,row.worker_account_id]);return Boolean(r.rows[0]);}const r=await db.query(`SELECT 1 FROM worker_evidence_versions v JOIN worker_evidence_records rec ON rec.record_id=v.record_id WHERE v.version_id=$1 AND rec.record_id=$2 AND rec.worker_account_id=$3 AND rec.current_version_id=v.version_id AND v.version_status='submitted'`,[row.source_version_id,row.source_record_id,row.worker_account_id]);return Boolean(r.rows[0]);}
 private async advanceCase(db:DatabaseClient,row:TaskRow,outcome:EvidenceReviewOutcome,now:Date,p:AuthorizationPrincipal){let status:string,owner:string|null,next:string|null;if(outcome==='CHANGES_REQUESTED'){status='Evidence pending';owner='worker';next='Correct the reviewed evidence and submit a new version.';}else if(outcome==='REJECTED'){status='Rejected';owner=null;next=null;}else{const pending=await db.query(`SELECT 1 FROM evidence_review_tasks WHERE case_id=$1 AND task_id<>$2 AND task_status NOT IN ('APPROVED','REJECTED','CHANGES_REQUESTED','SUPERSEDED','CANCELLED') LIMIT 1`,[row.case_id,row.task_id]);if(pending.rows[0]){status='Review pending';owner='reviewer';next='Wait for the remaining evidence review tasks.';}else{status='Assessment pending';owner='background_job';next='Await framework and effective-policy evaluation.';}}const old=await db.query<{case_status:string}>(`SELECT case_status FROM assurance_cases WHERE case_id=$1 AND tenant_id=$2 FOR UPDATE`,[row.case_id,row.tenant_id]);if(!old.rows[0])throw new EvidenceReviewAccessError();await db.query(`UPDATE assurance_cases SET case_status=$3,owner_kind=$4,next_action=$5,updated_at=$6,closed_at=CASE WHEN $3='Rejected' THEN $6 ELSE closed_at END WHERE case_id=$1 AND tenant_id=$2`,[row.case_id,row.tenant_id,status,owner,next,now.toISOString()]);await db.query(`INSERT INTO assurance_case_timeline_events(timeline_event_id,tenant_id,order_id,case_id,event_type,from_status,to_status,owner_kind,next_action,actor_account_id,actor_role,occurred_at) SELECT $1,c.tenant_id,c.order_id,c.case_id,'evidence_review_decision',$2,$3,$4,$5,$6,'verifier',$7 FROM assurance_cases c WHERE c.case_id=$8`,[createIdentifier("assurance_event"),old.rows[0].case_status,status,owner,next,p.accountId,now.toISOString(),row.case_id]);}
 async queueCaseEvidence(principal:TenantPermissionPrincipal<"company.orders.manage">,caseId:string,now=new Date()):Promise<number>{const scope=deriveTrustedTenantScope(principal);return this.database.transaction(async db=>{const c=await db.query<{worker_account_id:string;order_id:string}>(`SELECT worker_account_id,order_id FROM assurance_cases WHERE case_id=$1 AND tenant_id=$2 FOR UPDATE`,[caseId,scope.tenantId]);const ca=c.rows[0];if(!ca)throw new EvidenceReviewAccessError();const order=await db.query<{requested_identity_checks:unknown;requested_evidence_checks:unknown}>(`SELECT requested_identity_checks,requested_evidence_checks FROM assurance_orders WHERE order_id=$1 AND tenant_id=$2`,[ca.order_id,scope.tenantId]);if(!order.rows[0])throw new EvidenceReviewAccessError();const identityRequested=Array.isArray(order.rows[0].requested_identity_checks)?order.rows[0].requested_identity_checks.length>0:JSON.parse(String(order.rows[0].requested_identity_checks??"[]")).length>0;const evidenceRaw=Array.isArray(order.rows[0].requested_evidence_checks)?order.rows[0].requested_evidence_checks:JSON.parse(String(order.rows[0].requested_evidence_checks??"[]"));let count=0;if(identityRequested){const i=await db.query<{identity_id:string;identity_version_id:string;secure_file_id:string|null}>(`SELECT i.identity_id,v.identity_version_id,b.secure_file_id FROM worker_identities i JOIN worker_identity_versions v ON v.identity_id=i.identity_id AND v.version_number=i.current_version_number LEFT JOIN worker_identity_evidence_bindings b ON b.identity_version_id=v.identity_version_id AND b.purpose='identity_document' AND b.binding_status='active' WHERE i.worker_account_id=$1 AND v.version_status='submitted'`,[ca.worker_account_id]);if(i.rows[0])count+=await this.insertTask(db,scope.tenantId,caseId,ca.worker_account_id,'identity',i.rows[0].identity_id,i.rows[0].identity_version_id,i.rows[0].secure_file_id,'Identity document',now);}
 for(const kind of evidenceRaw.filter((v:unknown):v is string=>typeof v==='string'&&['qualification','experience','employment','skill'].includes(v))){const e=await db.query<{record_id:string;version_id:string;secure_file_id:string|null}>(`SELECT rec.record_id,v.version_id,a.secure_file_id FROM worker_evidence_records rec JOIN worker_evidence_versions v ON v.version_id=rec.current_version_id LEFT JOIN LATERAL (SELECT secure_file_id FROM worker_evidence_attachments WHERE version_id=v.version_id AND superseded_at IS NULL ORDER BY created_at LIMIT 1) a ON TRUE WHERE rec.worker_account_id=$1 AND rec.record_kind=$2 AND v.version_status='submitted' ORDER BY rec.updated_at DESC LIMIT 1`,[ca.worker_account_id,kind]);if(e.rows[0])count+=await this.insertTask(db,scope.tenantId,caseId,ca.worker_account_id,kind as EvidenceReviewKind,e.rows[0].record_id,e.rows[0].version_id,e.rows[0].secure_file_id,`${kind} evidence`,now);}
 const obs=await db.query<{observation_id:string;competency_reference:string}>(`SELECT observation_id,competency_reference FROM supervisor_observations WHERE tenant_id=$1 AND case_id=$2 AND worker_account_id=$3 AND observation_status='submitted'`,[scope.tenantId,caseId,ca.worker_account_id]);for(const o of obs.rows)count+=await this.insertTask(db,scope.tenantId,caseId,ca.worker_account_id,'supervisor_observation',o.observation_id,o.observation_id,null,`Supervisor observation: ${o.competency_reference}`,now);
 const taskState=await db.query<{total_count:number|string;actionable_count:number|string}>(`SELECT COUNT(*)::int AS total_count,COUNT(*) FILTER (WHERE task_status IN ('QUEUED','ASSIGNED'))::int AS actionable_count FROM evidence_review_tasks WHERE case_id=$1`,[caseId]);const total=Number(taskState.rows[0]?.total_count??0),actionable=Number(taskState.rows[0]?.actionable_count??0);
 if(actionable>0)await db.query(`UPDATE assurance_cases SET case_status='Review pending',owner_kind='reviewer',next_action='Reviewer must verify the queued evidence.',updated_at=$3 WHERE case_id=$1 AND tenant_id=$2`,[caseId,scope.tenantId,now.toISOString()]);else if(total===0)await db.query(`UPDATE assurance_cases SET case_status='Evidence pending',owner_kind='worker',next_action='Submit the required current evidence before review.',updated_at=$3 WHERE case_id=$1 AND tenant_id=$2`,[caseId,scope.tenantId,now.toISOString()]);return count;});}
 private async insertTask(db:DatabaseClient,tenantId:string,caseId:string,workerId:string,kind:EvidenceReviewKind,recordId:string,versionId:string,fileId:string|null,label:string,now:Date){const r=await db.query(`INSERT INTO evidence_review_tasks(task_id,tenant_id,case_id,worker_account_id,evidence_kind,source_record_id,source_version_id,secure_file_id,evidence_label,task_status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'QUEUED',$10,$10) ON CONFLICT(case_id,evidence_kind,source_version_id) DO NOTHING`,[createReviewTaskId(),tenantId,caseId,workerId,kind,recordId,versionId,fileId,label,now.toISOString()]);return r.affectedRows===1?1:0;}
 async addSupervisorObservation(principal:TenantPermissionPrincipal<"company.orders.manage">,input:{caseId:string;competencyReference:string;observedAt:Date;observationText:string;outcome:string},now=new Date()){const scope=deriveTrustedTenantScope(principal);const competency=input.competencyReference.trim(),text=input.observationText.trim();if(competency.length<2||competency.length>160||text.length<20||text.length>6000||!['demonstrated','partially_demonstrated','not_demonstrated'].includes(input.outcome))throw new EvidenceReviewInputError();return this.database.transaction(async db=>{const c=await db.query<{worker_account_id:string}>(`SELECT worker_account_id FROM assurance_cases WHERE case_id=$1 AND tenant_id=$2`,[input.caseId,scope.tenantId]);if(!c.rows[0])throw new EvidenceReviewAccessError();const id=createSupervisorObservationId();await db.query(`INSERT INTO supervisor_observations(observation_id,tenant_id,case_id,worker_account_id,competency_reference,observer_membership_id,observed_at,observation_text,outcome,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,scope.tenantId,input.caseId,c.rows[0].worker_account_id,competency,scope.membershipId,input.observedAt.toISOString(),text,input.outcome,now.toISOString()]);return id;});}
 async preview(principal:AuthorizationPrincipal,taskId:string,now=new Date()){assertVerifierPrincipal(principal);const t=await this.findTask(principal,taskId);if(!t||t.assignedVerifierAccountId!==principal.accountId||!t.secureFileId)throw new EvidenceReviewAccessError();const env=getServerEnvironment();if(env.appEnvironment!=='development'&&env.appEnvironment!=='test')throw new EvidenceReviewAccessError();const lookup=this.delegatedLookup(t);const issued=await authorizeSecureFileAccessCore({principal,fileRef:t.secureFileId,purpose:'preview',signingSecret:env.sessionSecret,repository:lookup,now});return readSecureFileAccessCore({principal,token:issued.token,expectedPurpose:'preview',signingSecret:env.sessionSecret,repository:lookup,storage:createLocalTestPrivateObjectStorage(env.appEnvironment),now});}
 private delegatedLookup(t:EvidenceReviewTask):SecureFileAccessLookup{return {findForPrincipal:async(principal,fileId)=>{assertVerifierPrincipal(principal);if(principal.accountId!==t.assignedVerifierAccountId||fileId!==t.secureFileId)return null;const r=await this.database.query<DelegatedSecureFileRow>(`SELECT * FROM platform_secure_files WHERE file_id=$1 AND lifecycle_status='available'`,[fileId]);const x=r.rows[0];if(!x)return null;return Object.freeze({sequence:Number(x.file_sequence),fileId:x.file_id,schemaVersion:Number(x.schema_version),reservationKey:x.reservation_key,ownerAccountId:x.owner_account_id,ownerRole:x.owner_role,tenantId:x.tenant_id,membershipId:x.membership_id,storageAdapterKey:x.storage_adapter_key,objectKey:x.object_key,displayFilename:x.display_filename,lifecycleStatus:x.lifecycle_status,fileExtension:x.file_extension,declaredMime:x.declared_mime,detectedMime:x.detected_mime,byteSize:x.byte_size===null?null:Number(x.byte_size),contentSha256:x.content_sha256,quarantinedAt:maybe(x.quarantined_at),availableAt:maybe(x.available_at),unsafeAt:maybe(x.unsafe_at),createdAt:iso(x.created_at),updatedAt:iso(x.updated_at)}) as SecureFileRecord;}};}
}
export async function getEvidenceReviewService(){return new EvidenceReviewService(await getDatabaseClient());}