import "server-only";
import type { DatabaseClient } from "../database/database";
import { getDatabaseClient } from "../database/database";
import type { QuestionDifficulty,QuestionType } from "./question-bank-domain";

type DeliveryRow={question_id:string;question_version_id:string;question_type:QuestionType;prompt:string;options_json:unknown;framework_id:string;domain_reference:string;difficulty:QuestionDifficulty;tags_json:unknown};
export type QuestionDeliveryProjection=Readonly<{questionId:string;questionVersionId:string;questionType:QuestionType;prompt:string;options:readonly string[]|null;frameworkId:string;domainReference:string;difficulty:QuestionDifficulty;tags:readonly string[]}>;
function strings(value:unknown):readonly string[]{const parsed=typeof value==="string"?JSON.parse(value):value;if(!Array.isArray(parsed)||parsed.some(v=>typeof v!=="string"))throw new Error("Question delivery metadata is invalid.");return Object.freeze(parsed as string[]);}
function project(row:DeliveryRow):QuestionDeliveryProjection{return Object.freeze({questionId:row.question_id,questionVersionId:row.question_version_id,questionType:row.question_type,prompt:row.prompt,options:row.options_json===null?null:strings(row.options_json),frameworkId:row.framework_id,domainReference:row.domain_reference,difficulty:row.difficulty,tags:strings(row.tags_json)});}
export class QuestionDeliveryService{constructor(private readonly database:DatabaseClient){}async findActiveVersion(questionVersionId:string):Promise<QuestionDeliveryProjection|null>{if(!/^question_version_[A-Za-z0-9_-]{24}$/.test(questionVersionId))return null;const rows=await this.database.query<DeliveryRow>(`SELECT q.question_id,v.question_version_id,v.question_type,v.prompt,v.options_json,v.framework_id,v.domain_reference,v.difficulty,v.tags_json FROM assessment_questions q JOIN assessment_question_versions v ON v.question_version_id=q.current_version_id WHERE q.question_status='ACTIVE' AND v.question_version_id=$1`,[questionVersionId]);return rows.rows[0]?project(rows.rows[0]):null;}async listActive():Promise<readonly QuestionDeliveryProjection[]>{const rows=await this.database.query<DeliveryRow>(`SELECT q.question_id,v.question_version_id,v.question_type,v.prompt,v.options_json,v.framework_id,v.domain_reference,v.difficulty,v.tags_json FROM assessment_questions q JOIN assessment_question_versions v ON v.question_version_id=q.current_version_id WHERE q.question_status='ACTIVE' ORDER BY q.question_id`);return Object.freeze(rows.rows.map(project));}}
export async function getQuestionDeliveryService():Promise<QuestionDeliveryService>{return new QuestionDeliveryService(await getDatabaseClient());}
