import type { AssuranceCaseRecord, AssuranceOrderRecord } from "@/lib/assurance/assurance-order-domain";
import { addAssuranceOrderWorkerAction, cancelAssuranceOrderDraftAction, cancelSubmittedAssuranceOrderAction, removeAssuranceOrderWorkerAction, saveAssuranceOrderDraftAction, submitAssuranceOrderAction, validateAssuranceOrderAction } from "@/app/company/(portal)/assurance-orders/actions";

export function AssuranceOrderWorkspace({order,cases}:{order:AssuranceOrderRecord;cases:readonly AssuranceCaseRecord[]}):React.JSX.Element{
 const editable=["DRAFT","VALIDATION_FAILED","READY"].includes(order.orderStatus); const submitted=["SUBMITTED","PARTIALLY_FUNDED","ACTIVE"].includes(order.orderStatus);
 return <div className="page-stack">
  <section className="detail-card"><h2>Order scope</h2><dl className="detail-grid"><div><dt>Name</dt><dd>{order.orderName}</dd></div><div><dt>Status</dt><dd>{order.orderStatus}</dd></div><div><dt>Deadline</dt><dd>{order.deadline?new Date(order.deadline).toLocaleString():"Not set"}</dd></div><div><dt>Scope version</dt><dd>{order.scopeVersion}</dd></div></dl>
   {order.validationErrors.length>0?<div role="alert" className="feedback feedback-error"><strong>Validation needs attention</strong><ul>{order.validationErrors.map(error=><li key={error}>{error}</li>)}</ul></div>:null}
  </section>
  {editable?<section className="form-card"><h2>Edit draft</h2><form action={saveAssuranceOrderDraftAction} className="form-grid"><input type="hidden" name="orderId" value={order.orderId}/><label>Order name<input name="orderName" defaultValue={order.orderName} required/></label><label>Order reference<input name="orderReference" defaultValue={order.orderReference} required/></label><label>Site reference<input name="siteId" defaultValue={order.siteId??""}/></label><label>Department reference<input name="departmentId" defaultValue={order.departmentId??""}/></label><label className="field-span">Requested identity checks<textarea name="requestedIdentityChecks" defaultValue={order.requestedIdentityChecks.join("\n")}/></label><label className="field-span">Requested evidence checks<textarea name="requestedEvidenceChecks" defaultValue={order.requestedEvidenceChecks.join("\n")}/></label><label className="field-span">Assessment framework references<textarea name="assessmentFrameworkReferences" defaultValue={order.assessmentFrameworkReferences.join("\n")}/></label><label><input type="checkbox" name="interviewRequired" defaultChecked={order.interviewRequired}/> Interview required</label><label>Credential target<input name="credentialTarget" defaultValue={order.credentialTarget??""}/></label><label>Deadline<input name="deadline" type="datetime-local" defaultValue={order.deadline?order.deadline.slice(0,16):""}/></label><label>Effective policy reference<input name="effectivePolicyReference" defaultValue={order.effectivePolicyReference??""}/></label><label className="field-span">Company notes<textarea name="companyNotes" defaultValue={order.companyNotes??""}/></label><label>Purchase order reference<input name="purchaseOrderReference" defaultValue={order.purchaseOrderReference??""}/></label><div className="field-span form-actions"><button type="submit">Save Draft</button></div></form>
   <form action={addAssuranceOrderWorkerAction} className="form-grid"><input type="hidden" name="orderId" value={order.orderId}/><label>Active Worker link ID<input name="workerLinkId" required/></label><label>Funding<select name="fundingMethod" defaultValue="worker"><option value="worker">Worker</option><option value="company">Company</option></select></label><button type="submit">Add Workers</button></form>
   <div className="form-actions"><form action={validateAssuranceOrderAction}><input type="hidden" name="orderId" value={order.orderId}/><button type="submit">Validate Order</button></form>{order.orderStatus==="READY"?<form action={submitAssuranceOrderAction}><input type="hidden" name="orderId" value={order.orderId}/><button type="submit">Submit Order</button></form>:null}<form action={cancelAssuranceOrderDraftAction}><input type="hidden" name="orderId" value={order.orderId}/><button className="button-danger" type="submit">Cancel Draft</button></form></div>
  </section>:null}
  {submitted?<form action={cancelSubmittedAssuranceOrderAction}><input type="hidden" name="orderId" value={order.orderId}/><button className="button-danger" type="submit">Cancel Submitted Order</button></form>:null}
  <section><h2>Worker cases</h2>{cases.length===0?<p>No Assurance Cases exist. Cases are created only after successful submission.</p>:<div className="table-scroll"><table><thead><tr><th>Worker</th><th>Status</th><th>Pending owner</th><th>Next action</th></tr></thead><tbody>{cases.map(item=><tr id={item.caseId} key={item.caseId}><td>{item.permanentWorkerId??item.workerAccountId}</td><td>{item.caseStatus}</td><td>{item.owner??"None"}</td><td>{item.nextAction??"No pending action"}</td></tr>)}</tbody></table></div>}</section>
 </div>;
}
