import "server-only";
import type { DatabaseClient } from "../database/database";
import { deriveTrustedTenantScope, type TenantPermissionPrincipal } from "../authorization/tenant-scoped-resource-domain";
import type { PolicyObject } from "./effective-policy-domain";

type SnapshotRow={case_id:string;worker_account_id:string;global_policy_version_id:string;tenant_override_id:string|null;policy_source:"GLOBAL"|"GLOBAL_PLUS_TENANT_OVERRIDE";effective_value_json:unknown;reference_time:string|Date;resolved_at:string|Date};
export type AssuranceCasePolicyView=Readonly<{caseId:string;workerAccountId:string;globalPolicyVersionId:string;tenantOverrideApplied:boolean;policySource:"GLOBAL"|"GLOBAL_PLUS_TENANT_OVERRIDE";effectiveValue:PolicyObject;referenceTime:string;resolvedAt:string}>;
const iso=(value:string|Date)=>value instanceof Date?value.toISOString():new Date(value).toISOString();
function object(value:unknown):PolicyObject{const parsed=typeof value==="string"?JSON.parse(value):value;if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("Stored effective policy snapshot is invalid.");return Object.freeze(parsed as Record<string,unknown>);}
export async function listAssuranceOrderPolicySnapshots(database:DatabaseClient,principal:TenantPermissionPrincipal<"company.orders.read">,orderId:string):Promise<readonly AssuranceCasePolicyView[]>{const scope=deriveTrustedTenantScope(principal);const rows=await database.query<SnapshotRow>(`SELECT s.case_id,c.worker_account_id,s.global_policy_version_id,s.tenant_override_id,s.policy_source,s.effective_value_json,s.reference_time,s.resolved_at FROM assurance_case_policy_snapshots s JOIN assurance_cases c ON c.case_id=s.case_id AND c.tenant_id=s.tenant_id WHERE s.tenant_id=$1 AND c.order_id=$2 ORDER BY c.created_at,c.case_id`,[scope.tenantId,orderId]);return Object.freeze(rows.rows.map(row=>Object.freeze({caseId:row.case_id,workerAccountId:row.worker_account_id,globalPolicyVersionId:row.global_policy_version_id,tenantOverrideApplied:Boolean(row.tenant_override_id),policySource:row.policy_source,effectiveValue:object(row.effective_value_json),referenceTime:iso(row.reference_time),resolvedAt:iso(row.resolved_at)})));}
