import "server-only";
import type { DatabaseClient } from "../database/database";
import { getDatabaseClient } from "../database/database";
import { runTenantScopedCommand } from "../authorization/tenant-scoped-command-guard";
import type { AuthorizationPrincipal } from "../authorization/authorization-context-domain";
import { deriveTrustedTenantScope, type TenantPermissionPrincipal } from "../authorization/tenant-scoped-resource-domain";
import { DatabaseAuditRepository } from "../audit/audit-repository";
import { bindTrustedAuditActor } from "../audit/audit-domain";
import {
  POLICY_TENANT_PERMISSION,EffectivePolicyAccessError,EffectivePolicyConflictError,EffectivePolicyInputError,
  assertTighteningOverride,createFrameworkId,createPolicyId,createPolicyOverrideId,createPolicySnapshotId,createPolicyVersionId,
  mergePolicy,normalizeAllowedFields,normalizeDirections,normalizePolicyObject,normalizePolicyReference,normalizePolicyTitle,
  type EffectivePolicyResolution,type EffectivePolicySnapshot,type OverrideDirection,type PolicyObject
} from "./effective-policy-domain";

type FrameworkRow={framework_id:string;framework_reference:string;title:string;framework_status:string};
type PolicyPackRow={policy_id:string;framework_id:string;policy_reference:string;title:string;policy_status:string;framework_reference:string};
type VersionRow={policy_version_id:string;policy_id:string;version_no:number|string;effective_from:string|Date;effective_to:string|Date|null;policy_values:unknown;override_allowed_fields:unknown;override_directions:unknown};
type OverrideRow={override_id:string;tenant_id:string;policy_id:string;version_no:number|string;override_values:unknown;effective_from:string|Date;effective_to:string|Date|null};
type SnapshotRow={snapshot_id:string;case_id:string;tenant_id:string;framework_id:string;policy_id:string;global_policy_version_id:string;tenant_override_id:string|null;policy_source:"GLOBAL"|"GLOBAL_PLUS_TENANT_OVERRIDE";effective_value_json:unknown;reference_time:string|Date;resolved_at:string|Date};
const iso=(v:string|Date)=>v instanceof Date?v.toISOString():new Date(v).toISOString();
function dateValue(value:string|Date,label:string):Date{const d=value instanceof Date?value:new Date(value);if(!Number.isFinite(d.getTime()))throw new EffectivePolicyInputError(`${label} is invalid.`);return d;}
function objectFromDb(value:unknown,label:string):PolicyObject{if(typeof value==="string"){try{return normalizePolicyObject(JSON.parse(value),label);}catch{throw new EffectivePolicyConflictError(`${label} is unreadable.`);}}return normalizePolicyObject(value,label);}
function stringArray(value:unknown):readonly string[]{const v=typeof value==="string"?JSON.parse(value):value;if(!Array.isArray(v)||v.some(x=>typeof x!=="string"))throw new EffectivePolicyConflictError("override_allowed_fields is invalid.");return Object.freeze(v as string[]);}
function directionMap(value:unknown):Readonly<Record<string,OverrideDirection>>{const v=typeof value==="string"?JSON.parse(value):value;if(!v||typeof v!=="object"||Array.isArray(v))throw new EffectivePolicyConflictError("override_directions is invalid.");return Object.freeze(v as Record<string,OverrideDirection>);}
async function liveAdmin(db:DatabaseClient,p:AuthorizationPrincipal,now:Date){if(p.activeRole!=="admin"||p.accountStatus!=="active")throw new EffectivePolicyAccessError();const r=await db.query(`SELECT 1 FROM auth_sessions s JOIN auth_accounts a ON a.account_id=s.account_id JOIN auth_account_roles ar ON ar.account_id=a.account_id AND ar.role='admin' WHERE s.session_id=$1 AND s.account_id=$2 AND s.active_role='admin' AND s.revoked_at IS NULL AND s.expires_at>$3 AND a.account_status='active' FOR UPDATE OF s,a`,[p.sessionId,p.accountId,now.toISOString()]);if(!r.rows[0])throw new EffectivePolicyAccessError();}
async function policyPack(db:DatabaseClient,policyReference:string):Promise<PolicyPackRow|null>{const r=await db.query<PolicyPackRow>(`SELECT p.policy_id,p.framework_id,p.policy_reference,p.title,p.policy_status,f.framework_reference FROM assurance_policy_packs p JOIN assurance_frameworks f ON f.framework_id=p.framework_id WHERE p.policy_reference=$1 AND p.policy_status='ACTIVE' AND f.framework_status='ACTIVE'`,[policyReference]);return r.rows[0]??null;}
async function activeVersions(db:DatabaseClient,policyId:string,at:Date):Promise<readonly VersionRow[]>{const r=await db.query<VersionRow>(`SELECT policy_version_id,policy_id,version_no,effective_from,effective_to,policy_values,override_allowed_fields,override_directions FROM assurance_policy_versions WHERE policy_id=$1 AND version_status='PUBLISHED' AND effective_from<=$2 AND (effective_to IS NULL OR effective_to>$2) ORDER BY version_no DESC`,[policyId,at.toISOString()]);return r.rows;}
async function activeOverrides(db:DatabaseClient,tenantId:string,policyId:string,at:Date):Promise<readonly OverrideRow[]>{const r=await db.query<OverrideRow>(`SELECT override_id,tenant_id,policy_id,version_no,override_values,effective_from,effective_to FROM tenant_policy_overrides WHERE tenant_id=$1 AND policy_id=$2 AND override_status='ACTIVE' AND effective_from<=$3 AND (effective_to IS NULL OR effective_to>$3) ORDER BY version_no DESC`,[tenantId,policyId,at.toISOString()]);return r.rows;}
async function audit(db:DatabaseClient,p:AuthorizationPrincipal,action:"assurance_order.updated"|"assurance_case.status.changed",ref:string,metadata:Record<string,unknown>){await new DatabaseAuditRepository(Promise.resolve(db)).append(bindTrustedAuditActor(p),{action,outcome:"succeeded",target:{type:"resource",reference:ref},metadata});}
function snapshot(row:SnapshotRow):EffectivePolicySnapshot{return Object.freeze({snapshotId:row.snapshot_id,caseId:row.case_id,tenantId:row.tenant_id,frameworkId:row.framework_id,policyId:row.policy_id,globalPolicyVersionId:row.global_policy_version_id,tenantOverrideId:row.tenant_override_id,policySource:row.policy_source,effectiveValue:objectFromDb(row.effective_value_json,"effective snapshot"),referenceTime:iso(row.reference_time),resolvedAt:iso(row.resolved_at)});}

export async function resolveEffectivePolicy(database:DatabaseClient,input:{tenantId:string;frameworkReferences:readonly string[];policyReference:string;referenceTime:Date}):Promise<EffectivePolicyResolution>{
 const policyRef=normalizePolicyReference(input.policyReference,"policy reference");const refs=input.frameworkReferences.map(v=>normalizePolicyReference(v,"framework reference"));const pack=await policyPack(database,policyRef);if(!pack)throw new EffectivePolicyConflictError("Effective policy reference is unavailable.");if(refs.length>0&&!refs.includes(pack.framework_reference))throw new EffectivePolicyConflictError("Effective policy does not belong to a selected framework.");
 const versions=await activeVersions(database,pack.policy_id,input.referenceTime);if(versions.length!==1)throw new EffectivePolicyConflictError(versions.length===0?"Effective policy has a version gap.":"Effective policy version is ambiguous because active windows overlap.");const version=versions[0];const globalValues=objectFromDb(version.policy_values,"global policy");const allowed=stringArray(version.override_allowed_fields);const directions=directionMap(version.override_directions);
 const overrides=await activeOverrides(database,input.tenantId,pack.policy_id,input.referenceTime);if(overrides.length>1)throw new EffectivePolicyConflictError("Effective policy tenant override is ambiguous because active windows overlap.");const selected=overrides[0]??null;let effective=globalValues;if(selected){const values=objectFromDb(selected.override_values,"tenant override");assertTighteningOverride(globalValues,allowed,directions,values);effective=mergePolicy(globalValues,values);}
 return Object.freeze({frameworkId:pack.framework_id,policyId:pack.policy_id,globalPolicyVersionId:version.policy_version_id,tenantOverrideId:selected?.override_id??null,policySource:selected?"GLOBAL_PLUS_TENANT_OVERRIDE":"GLOBAL",effectiveValue:effective});
}

export async function validateAssurancePolicySelection(database:DatabaseClient,input:{tenantId:string;frameworkReferences:readonly string[];policyReference:string|null;referenceTime:Date}):Promise<readonly string[]>{const errors:string[]=[];const refs=[...new Set(input.frameworkReferences.map(v=>v.trim()).filter(Boolean))];for(const ref of refs){const row=await database.query(`SELECT 1 FROM assurance_frameworks WHERE framework_reference=$1 AND framework_status='ACTIVE'`,[ref]);if(!row.rows[0])errors.push(`Assessment framework ${ref} is unavailable.`);}if(!input.policyReference){if(refs.length>0)errors.push("Select an effective policy for the assessment framework.");return Object.freeze(errors);}try{await resolveEffectivePolicy(database,{tenantId:input.tenantId,frameworkReferences:refs,policyReference:input.policyReference,referenceTime:input.referenceTime});}catch(error){errors.push(error instanceof Error?error.message:"Effective policy could not be resolved.");}return Object.freeze(errors);}

export async function pinAssuranceCasePolicySnapshot(database:DatabaseClient,input:{caseId:string;tenantId:string;frameworkReferences:readonly string[];policyReference:string|null;referenceTime:Date;actorAccountId:string|null;actorPrincipal?:AuthorizationPrincipal}):Promise<EffectivePolicySnapshot|null>{if(!input.policyReference)return null;return database.transaction(async db=>{const existing=await db.query<SnapshotRow>(`SELECT * FROM assurance_case_policy_snapshots WHERE case_id=$1 AND tenant_id=$2`,[input.caseId,input.tenantId]);if(existing.rows[0])return snapshot(existing.rows[0]);const resolution=await resolveEffectivePolicy(db,{tenantId:input.tenantId,frameworkReferences:input.frameworkReferences,policyReference:input.policyReference,referenceTime:input.referenceTime});const id=createPolicySnapshotId();await db.query(`INSERT INTO assurance_case_policy_snapshots(snapshot_id,case_id,tenant_id,framework_id,policy_id,global_policy_version_id,tenant_override_id,policy_source,effective_value_json,reference_time,resolved_at,created_by_account_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12) ON CONFLICT(case_id) DO NOTHING`,[id,input.caseId,input.tenantId,resolution.frameworkId,resolution.policyId,resolution.globalPolicyVersionId,resolution.tenantOverrideId,resolution.policySource,JSON.stringify(resolution.effectiveValue),input.referenceTime.toISOString(),new Date().toISOString(),input.actorAccountId]);const row=await db.query<SnapshotRow>(`SELECT * FROM assurance_case_policy_snapshots WHERE case_id=$1 AND tenant_id=$2`,[input.caseId,input.tenantId]);if(!row.rows[0])throw new EffectivePolicyConflictError("Effective policy snapshot could not be pinned.");if(input.actorPrincipal)await audit(db,input.actorPrincipal,"assurance_case.status.changed",input.caseId,{policyPinCreated:true,overrideApplied:Boolean(row.rows[0].tenant_override_id)});return snapshot(row.rows[0]);});}

export class EffectivePolicyService{
 constructor(private readonly database:DatabaseClient){}
 async createFramework(principal:AuthorizationPrincipal,input:{reference:string;title:string},now=new Date()):Promise<string>{const ref=normalizePolicyReference(input.reference,"framework reference"),title=normalizePolicyTitle(input.title);return this.database.transaction(async db=>{await liveAdmin(db,principal,now);const id=createFrameworkId();try{await db.query(`INSERT INTO assurance_frameworks(framework_id,framework_reference,title,created_by_account_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$5)`,[id,ref,title,principal.accountId,now.toISOString()]);}catch(error){if((error as {code?:string})?.code==="23505")throw new EffectivePolicyConflictError("Framework reference already exists.");throw error;}return id;});}
 async publishPolicyVersion(principal:AuthorizationPrincipal,input:{frameworkReference:string;policyReference:string;title:string;effectiveFrom:Date;effectiveTo:Date|null;policyValues:unknown;overrideAllowedFields:readonly string[];overrideDirections:Record<string,string>},now=new Date()):Promise<string>{const frameworkRef=normalizePolicyReference(input.frameworkReference,"framework reference"),policyRef=normalizePolicyReference(input.policyReference,"policy reference"),title=normalizePolicyTitle(input.title),values=normalizePolicyObject(input.policyValues),allowed=normalizeAllowedFields(input.overrideAllowedFields),directions=normalizeDirections(input.overrideDirections,allowed,values),from=dateValue(input.effectiveFrom,"effective from"),to=input.effectiveTo?dateValue(input.effectiveTo,"effective to"):null;if(to&&to<=from)throw new EffectivePolicyInputError("Effective policy window is invalid.");return this.database.transaction(async db=>{await liveAdmin(db,principal,now);const fr=await db.query<FrameworkRow>(`SELECT framework_id,framework_reference,title,framework_status FROM assurance_frameworks WHERE framework_reference=$1 AND framework_status='ACTIVE' FOR UPDATE`,[frameworkRef]);if(!fr.rows[0])throw new EffectivePolicyAccessError();let pack=await policyPack(db,policyRef);if(pack&&pack.framework_id!==fr.rows[0].framework_id)throw new EffectivePolicyConflictError("Policy reference belongs to another framework.");if(!pack){const policyId=createPolicyId();await db.query(`INSERT INTO assurance_policy_packs(policy_id,framework_id,policy_reference,title,created_by_account_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$6)`,[policyId,fr.rows[0].framework_id,policyRef,title,principal.accountId,now.toISOString()]);pack=await policyPack(db,policyRef);if(!pack)throw new EffectivePolicyConflictError("Policy pack could not be created.");}const overlap=await db.query(`SELECT 1 FROM assurance_policy_versions WHERE policy_id=$1 AND version_status='PUBLISHED' AND effective_from<COALESCE($3,'infinity'::timestamptz) AND COALESCE(effective_to,'infinity'::timestamptz)>$2 LIMIT 1`,[pack.policy_id,from.toISOString(),to?.toISOString()??null]);if(overlap.rows[0])throw new EffectivePolicyConflictError("Published policy effective windows cannot overlap.");const next=await db.query<{version_no:number|string}>(`SELECT COALESCE(MAX(version_no),0)+1 AS version_no FROM assurance_policy_versions WHERE policy_id=$1`,[pack.policy_id]);const id=createPolicyVersionId();await db.query(`INSERT INTO assurance_policy_versions(policy_version_id,policy_id,version_no,effective_from,effective_to,policy_values,override_allowed_fields,override_directions,created_by_account_id,created_at) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8::jsonb,$9,$10)`,[id,pack.policy_id,Number(next.rows[0]?.version_no??1),from.toISOString(),to?.toISOString()??null,JSON.stringify(values),JSON.stringify(allowed),JSON.stringify(directions),principal.accountId,now.toISOString()]);return id;});}
 async saveTenantOverride(principal:TenantPermissionPrincipal<typeof POLICY_TENANT_PERMISSION>,input:{policyReference:string;overrideValues:unknown;effectiveFrom:Date;effectiveTo:Date|null},now=new Date()):Promise<string>{const policyRef=normalizePolicyReference(input.policyReference,"policy reference"),values=normalizePolicyObject(input.overrideValues,"tenant override"),from=dateValue(input.effectiveFrom,"effective from"),to=input.effectiveTo?dateValue(input.effectiveTo,"effective to"):null;if(to&&to<=from)throw new EffectivePolicyInputError("Tenant override window is invalid.");return runTenantScopedCommand({database:this.database,principal,permission:POLICY_TENANT_PERMISSION,now,operation:async({database,scope})=>{const pack=await policyPack(database,policyRef);if(!pack)throw new EffectivePolicyAccessError();const versions=await activeVersions(database,pack.policy_id,from);if(versions.length!==1)throw new EffectivePolicyConflictError("A unique global policy version is required before an override can be saved.");const global=objectFromDb(versions[0].policy_values,"global policy"),allowed=stringArray(versions[0].override_allowed_fields),directions=directionMap(versions[0].override_directions);assertTighteningOverride(global,allowed,directions,values);const overlap=await database.query(`SELECT 1 FROM tenant_policy_overrides WHERE tenant_id=$1 AND policy_id=$2 AND override_status='ACTIVE' AND effective_from<COALESCE($4,'infinity'::timestamptz) AND COALESCE(effective_to,'infinity'::timestamptz)>$3 LIMIT 1`,[scope.tenantId,pack.policy_id,from.toISOString(),to?.toISOString()??null]);if(overlap.rows[0])throw new EffectivePolicyConflictError("Tenant override effective windows cannot overlap.");const next=await database.query<{version_no:number|string}>(`SELECT COALESCE(MAX(version_no),0)+1 AS version_no FROM tenant_policy_overrides WHERE tenant_id=$1 AND policy_id=$2`,[scope.tenantId,pack.policy_id]);const id=createPolicyOverrideId();await database.query(`INSERT INTO tenant_policy_overrides(override_id,tenant_id,policy_id,version_no,override_values,effective_from,effective_to,created_by_membership_id,created_at) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9)`,[id,scope.tenantId,pack.policy_id,Number(next.rows[0]?.version_no??1),JSON.stringify(values),from.toISOString(),to?.toISOString()??null,scope.membershipId,now.toISOString()]);await audit(database,principal,"assurance_order.updated",pack.policy_id,{effectivePolicyOverrideCreated:true,overrideId:id});return id;}});}
 async listFrameworks(principal:AuthorizationPrincipal):Promise<readonly FrameworkRow[]>{if(principal.activeRole!=="admin")throw new EffectivePolicyAccessError();const r=await this.database.query<FrameworkRow>(`SELECT framework_id,framework_reference,title,framework_status FROM assurance_frameworks ORDER BY framework_reference`);return Object.freeze(r.rows);}
 async listTenantOverrides(principal:TenantPermissionPrincipal<typeof POLICY_TENANT_PERMISSION>):Promise<readonly {overrideId:string;policyReference:string;overrideValues:PolicyObject;effectiveFrom:string;effectiveTo:string|null}[]>{const tenant=deriveTrustedTenantScope(principal).tenantId;const r=await this.database.query<OverrideRow&{policy_reference:string}>(`SELECT o.*,p.policy_reference FROM tenant_policy_overrides o JOIN assurance_policy_packs p ON p.policy_id=o.policy_id WHERE o.tenant_id=$1 ORDER BY o.created_at DESC`,[tenant]);return Object.freeze(r.rows.map(v=>Object.freeze({overrideId:v.override_id,policyReference:v.policy_reference,overrideValues:objectFromDb(v.override_values,"tenant override"),effectiveFrom:iso(v.effective_from),effectiveTo:v.effective_to?iso(v.effective_to):null})));}
}
export async function getEffectivePolicyService(){return new EffectivePolicyService(await getDatabaseClient());}
