import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import test from "node:test";
import { openScriptDatabase } from "../../scripts/lib/database.mjs";
import { applyMigrationsThrough } from "../helpers/migration-ceiling.mjs";

const runtime=process.env.HSE_EFFECTIVE_POLICY_RUNTIME_DIST;assert.ok(runtime,"HSE_EFFECTIVE_POLICY_RUNTIME_DIST is required");
const domain=await import(pathToFileURL(join(runtime,"policy","effective-policy-domain.js")).href);
const serviceModule=await import(pathToFileURL(join(runtime,"policy","effective-policy-service.js")).href);
const assuranceModule=await import(pathToFileURL(join(runtime,"assurance","assurance-order-service.js")).href);
const {EffectivePolicyConflictError}=domain;
const {EffectivePolicyService,resolveEffectivePolicy,pinAssuranceCasePolicySnapshot}=serviceModule;
const {AssuranceOrderService}=assuranceModule;
const MIGRATION="0035_frameworks_effective_policy",NOW_DATE=new Date("2026-08-18T01:40:00.000Z"),NOW=NOW_DATE.toISOString(),FUTURE="2099-01-01T00:00:00.000Z";
const ENV={appEnvironment:"test",databaseDriver:"pglite",databaseUrl:null,pgliteDataDir:"memory://",releaseSha:"m2-03-policy-runtime-test",sessionSecret:"m2-03-session-secret-with-more-than-thirty-two-characters",authPepper:"m2-03-auth-pepper-with-more-than-thirty-two-characters",authSandboxEnabled:false,authSandboxAccessKey:null,demoAuthEnabled:false,demoDataEnabled:false};
const oid=(prefix,c)=>`${prefix}_${c.repeat(24)}`;
async function db(){const d=await openScriptDatabase(ENV);await applyMigrationsThrough(d,ENV.releaseSha,MIGRATION);return d;}
async function seedPolicy(database,c,{from="2026-01-01T00:00:00.000Z",to=null,values={pass_mark:80,max_attempts:2,recording_required:true},allowed=["pass_mark","max_attempts"],directions={pass_mark:"MINIMUM",max_attempts:"MAXIMUM"}}={}){const frameworkId=oid("framework",c),policyId=oid("policy",c),versionId=oid("policy_version",c);await database.query(`INSERT INTO assurance_frameworks(framework_id,framework_reference,title,created_by_account_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$5)`,[frameworkId,`FRAME-${c}`,`Framework ${c}`,`account_admin_${c}`,NOW]);await database.query(`INSERT INTO assurance_policy_packs(policy_id,framework_id,policy_reference,title,created_by_account_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$6)`,[policyId,frameworkId,`POLICY-${c}`,`Policy ${c}`,`account_admin_${c}`,NOW]);await database.query(`INSERT INTO assurance_policy_versions(policy_version_id,policy_id,version_no,effective_from,effective_to,policy_values,override_allowed_fields,override_directions,created_by_account_id,created_at) VALUES($1,$2,1,$3,$4,$5::jsonb,$6::jsonb,$7::jsonb,$8,$9)`,[versionId,policyId,from,to,JSON.stringify(values),JSON.stringify(allowed),JSON.stringify(directions),`account_admin_${c}`,NOW]);return{frameworkId,policyId,versionId,frameworkReference:`FRAME-${c}`,policyReference:`POLICY-${c}`};}
async function seedCompany(database,c){const x={accountId:`account_m203_company_${c}`,tenantId:oid("tenant",c),membershipId:oid("membership",c),sessionId:`session_m203_company_${c}`,email:`m203-${c.toLowerCase()}@example.com`};await database.query(`INSERT INTO auth_accounts(account_id,email_normalized,display_name,account_status,password_hash,email_verified_at,password_set_at,created_at,updated_at) VALUES($1,$2,$3,'active',$4,$5,$5,$5,$5)`,[x.accountId,x.email,`Company ${c}`,"scrypt$16384$8$1$salt$hash",NOW]);await database.query(`INSERT INTO auth_account_roles(account_id,role,created_at) VALUES($1,'company',$2)`,[x.accountId,NOW]);await database.query(`INSERT INTO platform_tenants(tenant_id,tenant_type,display_name,tenant_status,created_by_account_id,created_at,updated_at,activated_at) VALUES($1,'company',$2,'active',$3,$4,$4,$4)`,[x.tenantId,`Company ${c}`,x.accountId,NOW]);await database.query(`INSERT INTO auth_tenant_memberships(membership_id,tenant_id,account_id,portal_role,membership_role,membership_status,created_by_account_id,created_at,updated_at,activated_at) VALUES($1,$2,$3,'company','owner','active',$3,$4,$4,$4)`,[x.membershipId,x.tenantId,x.accountId,NOW]);await database.query(`INSERT INTO auth_sessions(session_id,account_id,active_role,token_hash,csrf_token_hash,created_at,last_seen_at,expires_at) VALUES($1,$2,'company',$3,$4,$5,$5,$6)`,[x.sessionId,x.accountId,`token-${c}`,`csrf-${c}`,NOW,FUTURE]);await database.query(`INSERT INTO company_verification_cases(case_id,tenant_id,owner_account_id,case_status,lock_version,created_at,updated_at,verified_at) VALUES($1,$2,$3,'verified',0,$4,$4,$4)`,[oid("company_verification",c),x.tenantId,x.accountId,NOW]);return x;}
const settingsPrincipal=x=>Object.freeze({accountId:x.accountId,sessionId:x.sessionId,activeRole:"company",accountStatus:"active",email:x.email,displayName:"Company",createdAt:NOW,lastSeenAt:NOW,expiresAt:FUTURE,tenantMembership:{tenantId:x.tenantId,tenantStatus:"active",membershipId:x.membershipId,role:"owner",status:"active",overrides:[]},authorizedTenantPermission:"company.settings.manage"});
const ordersPrincipal=x=>Object.freeze({...settingsPrincipal(x),authorizedTenantPermission:"company.orders.manage"});
async function seedWorker(database,company,c){const workerId=`account_m203_worker_${c}`,email=`worker-m203-${c.toLowerCase()}@example.com`;await database.query(`INSERT INTO auth_accounts(account_id,email_normalized,display_name,account_status,password_hash,email_verified_at,password_set_at,created_at,updated_at) VALUES($1,$2,$3,'active',$4,$5,$5,$5,$5)`,[workerId,email,`Worker ${c}`,"scrypt$16384$8$1$salt$hash",NOW]);await database.query(`INSERT INTO auth_account_roles(account_id,role,created_at) VALUES($1,'worker',$2)`,[workerId,NOW]);const invitationId=oid("worker_invitation",c),linkId=oid("company_worker_link",c);await database.query(`INSERT INTO company_worker_invitations(invitation_id,tenant_id,email_normalized,token_hash,invitation_status,site_id,department_id,payment_responsibility,assessment_reference,invited_by_membership_id,accepted_by_worker_account_id,resend_count,resend_available_at,expires_at,accepted_at,created_at,updated_at) VALUES($1,$2,$3,$4,'accepted',NULL,NULL,'worker',NULL,$5,$6,0,$7,$8,$7,$7,$7)`,[invitationId,company.tenantId,email,`hash-${c}`,company.membershipId,workerId,NOW,FUTURE]);await database.query(`INSERT INTO company_worker_links(link_id,tenant_id,worker_account_id,permanent_worker_id,link_source,invitation_id,code_id,link_status,site_id,department_id,payment_responsibility,assessment_reference,requested_by_membership_id,worker_accepted_at,activated_at,created_at,updated_at) VALUES($1,$2,$3,NULL,'invitation',$4,NULL,'active',NULL,NULL,'worker',NULL,$5,$6,$6,$6,$6)`,[linkId,company.tenantId,workerId,invitationId,company.membershipId,NOW]);return{workerId,linkId};}

test("M2.03 resolves global policy and a permitted tightening Company override",async()=>{const d=await db();try{const p=await seedPolicy(d,"A"),company=await seedCompany(d,"B");const base=await resolveEffectivePolicy(d,{tenantId:company.tenantId,frameworkReferences:[p.frameworkReference],policyReference:p.policyReference,referenceTime:NOW_DATE});assert.equal(base.policySource,"GLOBAL");assert.equal(base.effectiveValue.pass_mark,80);const service=new EffectivePolicyService(d);await service.saveTenantOverride(settingsPrincipal(company),{policyReference:p.policyReference,overrideValues:{pass_mark:85,max_attempts:1},effectiveFrom:new Date("2026-08-01T00:00:00Z"),effectiveTo:null},NOW_DATE);const resolved=await resolveEffectivePolicy(d,{tenantId:company.tenantId,frameworkReferences:[p.frameworkReference],policyReference:p.policyReference,referenceTime:NOW_DATE});assert.equal(resolved.policySource,"GLOBAL_PLUS_TENANT_OVERRIDE");assert.equal(resolved.effectiveValue.pass_mark,85);assert.equal(resolved.effectiveValue.max_attempts,1);}finally{await d.close();}});

test("M2.03 rejects disallowed and weakening overrides and never leaks them across tenants",async()=>{const d=await db();try{const p=await seedPolicy(d,"C"),a=await seedCompany(d,"D"),b=await seedCompany(d,"E"),service=new EffectivePolicyService(d);await assert.rejects(service.saveTenantOverride(settingsPrincipal(a),{policyReference:p.policyReference,overrideValues:{recording_required:false},effectiveFrom:NOW_DATE,effectiveTo:null},NOW_DATE),EffectivePolicyConflictError);await assert.rejects(service.saveTenantOverride(settingsPrincipal(a),{policyReference:p.policyReference,overrideValues:{pass_mark:60},effectiveFrom:NOW_DATE,effectiveTo:null},NOW_DATE),EffectivePolicyConflictError);await service.saveTenantOverride(settingsPrincipal(a),{policyReference:p.policyReference,overrideValues:{pass_mark:90},effectiveFrom:NOW_DATE,effectiveTo:null},NOW_DATE);const other=await resolveEffectivePolicy(d,{tenantId:b.tenantId,frameworkReferences:[p.frameworkReference],policyReference:p.policyReference,referenceTime:NOW_DATE});assert.equal(other.policySource,"GLOBAL");assert.equal(other.effectiveValue.pass_mark,80);}finally{await d.close();}});

test("M2.03 fails closed on policy gaps and overlapping active versions",async()=>{const d=await db();try{const gap=await seedPolicy(d,"F",{from:"2027-01-01T00:00:00Z"});await assert.rejects(resolveEffectivePolicy(d,{tenantId:oid("tenant","G"),frameworkReferences:[gap.frameworkReference],policyReference:gap.policyReference,referenceTime:NOW_DATE}),EffectivePolicyConflictError);const p=await seedPolicy(d,"H");await d.query(`INSERT INTO assurance_policy_versions(policy_version_id,policy_id,version_no,effective_from,effective_to,policy_values,override_allowed_fields,override_directions,created_by_account_id,created_at) VALUES($1,$2,2,$3,NULL,$4::jsonb,$5::jsonb,$6::jsonb,$7,$8)`,[oid("policy_version","I"),p.policyId,"2026-06-01T00:00:00Z",JSON.stringify({pass_mark:82}),JSON.stringify(["pass_mark"]),JSON.stringify({pass_mark:"MINIMUM"}),"account_admin_I",NOW]);await assert.rejects(resolveEffectivePolicy(d,{tenantId:oid("tenant","J"),frameworkReferences:[p.frameworkReference],policyReference:p.policyReference,referenceTime:NOW_DATE}),error=>error instanceof EffectivePolicyConflictError&&/ambiguous/i.test(error.message));}finally{await d.close();}});

test("M2.03 concurrent snapshot pinning creates one immutable snapshot and later policy rows cannot rewrite it",async()=>{const d=await db();try{const p=await seedPolicy(d,"K"),tenantId=oid("tenant","L"),caseId=oid("assurance_case","M");const calls=await Promise.all(Array.from({length:8},()=>pinAssuranceCasePolicySnapshot(d,{caseId,tenantId,frameworkReferences:[p.frameworkReference],policyReference:p.policyReference,referenceTime:NOW_DATE,actorAccountId:null})));assert.equal(new Set(calls.map(x=>x.snapshotId)).size,1);const rows=await d.query(`SELECT * FROM assurance_case_policy_snapshots WHERE case_id=$1`,[caseId]);assert.equal(rows.rows.length,1);assert.equal(rows.rows[0].global_policy_version_id,p.versionId);await assert.rejects(d.query(`UPDATE assurance_case_policy_snapshots SET policy_source='GLOBAL_PLUS_TENANT_OVERRIDE' WHERE case_id=$1`,[caseId]),e=>e?.code==="55000");await assert.rejects(d.query(`DELETE FROM assurance_case_policy_snapshots WHERE case_id=$1`,[caseId]),e=>e?.code==="55000");}finally{await d.close();}});

test("M2.03 M2.01 integration validates a real policy and pins it to every submitted case",async()=>{const d=await db();try{const p=await seedPolicy(d,"N"),company=await seedCompany(d,"O"),worker=await seedWorker(d,company,"P"),service=new AssuranceOrderService(d),principal=ordersPrincipal(company);const order=await service.createDraft(principal,{orderName:"Policy order",orderReference:"M203-POLICY",siteId:null,departmentId:null,requestedIdentityChecks:["identity"],requestedEvidenceChecks:["qualification"],assessmentFrameworkReferences:[p.frameworkReference],interviewRequired:false,credentialTarget:null,deadline:"2026-08-25T00:00:00.000Z",effectivePolicyReference:p.policyReference,companyNotes:"Policy integration",purchaseOrderReference:null},NOW_DATE);await service.addWorkerTarget(principal,order.orderId,worker.linkId,"worker",NOW_DATE);const validation=await service.validateOrder(principal,order.orderId,NOW_DATE);assert.equal(validation.ready,true,validation.errors.join("; "));const cases=await service.submitOrder(principal,order.orderId,NOW_DATE);assert.equal(cases.length,1);const snap=await d.query(`SELECT global_policy_version_id,effective_value_json FROM assurance_case_policy_snapshots WHERE case_id=$1`,[cases[0].caseId]);assert.equal(snap.rows.length,1);assert.equal(snap.rows[0].global_policy_version_id,p.versionId);}finally{await d.close();}});

test("M2.03 history-preserving down/reapply retains pinned snapshots",async()=>{const d=await db();try{const p=await seedPolicy(d,"Q"),caseId=oid("assurance_case","R"),tenantId=oid("tenant","S");await pinAssuranceCasePolicySnapshot(d,{caseId,tenantId,frameworkReferences:[p.frameworkReference],policyReference:p.policyReference,referenceTime:NOW_DATE,actorAccountId:null});await d.execute(readFileSync("database/migrations/0035_frameworks_effective_policy.down.sql","utf8"));assert.equal((await d.query(`SELECT COUNT(*)::int AS count FROM assurance_case_policy_snapshots WHERE case_id=$1`,[caseId])).rows[0].count,1);await d.execute(readFileSync("database/migrations/0035_frameworks_effective_policy.up.sql","utf8"));assert.equal((await d.query(`SELECT COUNT(*)::int AS count FROM assurance_case_policy_snapshots WHERE case_id=$1`,[caseId])).rows[0].count,1);}finally{await d.close();}});
