import assert from "node:assert/strict";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import test from "node:test";
import { openScriptDatabase } from "../../scripts/lib/database.mjs";
import { applyMigrationsThrough } from "../helpers/migration-ceiling.mjs";

const runtime=process.env.HSE_EFFECTIVE_POLICY_RUNTIME_DIST;assert.ok(runtime,"HSE_EFFECTIVE_POLICY_RUNTIME_DIST is required");
const domain=await import(pathToFileURL(join(runtime,"policy","effective-policy-domain.js")).href);
const serviceModule=await import(pathToFileURL(join(runtime,"policy","effective-policy-service.js")).href);
const {EffectivePolicyAccessError,EffectivePolicyConflictError}=domain;
const {EffectivePolicyService,resolveEffectivePolicy}=serviceModule;
const NOW_DATE=new Date("2026-08-18T01:45:00.000Z"),NOW=NOW_DATE.toISOString(),FUTURE="2099-01-01T00:00:00.000Z";
const ENV={appEnvironment:"test",databaseDriver:"pglite",databaseUrl:null,pgliteDataDir:"memory://",releaseSha:"m2-03-policy-admin-runtime-test",sessionSecret:"m2-03-admin-session-secret-with-more-than-thirty-two-characters",authPepper:"m2-03-admin-auth-pepper-with-more-than-thirty-two-characters",authSandboxEnabled:false,authSandboxAccessKey:null,demoAuthEnabled:false,demoDataEnabled:false};
async function db(){const d=await openScriptDatabase(ENV);await applyMigrationsThrough(d,ENV.releaseSha,"0035_frameworks_effective_policy");return d;}
async function seedAdmin(database,suffix,{revoked=false}={}){const accountId=`account_m203_admin_${suffix}`,sessionId=`session_m203_admin_${suffix}`,email=`admin-m203-${suffix.toLowerCase()}@example.com`;await database.query(`INSERT INTO auth_accounts(account_id,email_normalized,display_name,account_status,password_hash,email_verified_at,password_set_at,created_at,updated_at) VALUES($1,$2,$3,'active',$4,$5,$5,$5,$5)`,[accountId,email,`Admin ${suffix}`,"scrypt$16384$8$1$salt$hash",NOW]);await database.query(`INSERT INTO auth_account_roles(account_id,role,created_at) VALUES($1,'admin',$2)`,[accountId,NOW]);await database.query(`INSERT INTO auth_sessions(session_id,account_id,active_role,token_hash,csrf_token_hash,created_at,last_seen_at,expires_at,revoked_at,revocation_reason) VALUES($1,$2,'admin',$3,$4,$5,$5,$6,$7,$8)`,[sessionId,accountId,`token-${suffix}`,`csrf-${suffix}`,NOW,FUTURE,revoked?NOW:null,revoked?"runtime_fixture_revoked":null]);return Object.freeze({accountId,sessionId,activeRole:"admin",accountStatus:"active",email,displayName:`Admin ${suffix}`,createdAt:NOW,lastSeenAt:NOW,expiresAt:FUTURE,tenantMembership:null,authorizedPlatformPermission:"platform.operations.manage"});}

test("M2.03 admin service publishes a real version only from a live fixed-role admin session",async()=>{const d=await db();try{const admin=await seedAdmin(d,"A"),service=new EffectivePolicyService(d);await service.createFramework(admin,{reference:"FRAME-ADMIN",title:"Admin Runtime Framework"},NOW_DATE);const versionId=await service.publishPolicyVersion(admin,{frameworkReference:"FRAME-ADMIN",policyReference:"POLICY-ADMIN",title:"Admin Runtime Policy",effectiveFrom:new Date("2026-01-01T00:00:00Z"),effectiveTo:null,policyValues:{pass_mark:80,max_attempts:2},overrideAllowedFields:["pass_mark","max_attempts"],overrideDirections:{pass_mark:"MINIMUM",max_attempts:"MAXIMUM"}},NOW_DATE);assert.match(versionId,/^policy_version_/);const resolved=await resolveEffectivePolicy(d,{tenantId:"tenant_ZZZZZZZZZZZZZZZZZZZZZZZZ",frameworkReferences:["FRAME-ADMIN"],policyReference:"POLICY-ADMIN",referenceTime:NOW_DATE});assert.equal(resolved.globalPolicyVersionId,versionId);assert.equal(resolved.effectiveValue.pass_mark,80);}finally{await d.close();}});

test("M2.03 admin publication rejects revoked sessions and overlapping version windows",async()=>{const d=await db();try{const live=await seedAdmin(d,"B"),revoked=await seedAdmin(d,"C",{revoked:true}),service=new EffectivePolicyService(d);await assert.rejects(service.createFramework(revoked,{reference:"FRAME-REVOKED",title:"Must not create"},NOW_DATE),EffectivePolicyAccessError);await service.createFramework(live,{reference:"FRAME-OVERLAP",title:"Overlap Framework"},NOW_DATE);const common={frameworkReference:"FRAME-OVERLAP",policyReference:"POLICY-OVERLAP",title:"Overlap Policy",policyValues:{pass_mark:80},overrideAllowedFields:["pass_mark"],overrideDirections:{pass_mark:"MINIMUM"}};await service.publishPolicyVersion(live,{...common,effectiveFrom:new Date("2026-01-01T00:00:00Z"),effectiveTo:new Date("2027-01-01T00:00:00Z")},NOW_DATE);await assert.rejects(service.publishPolicyVersion(live,{...common,effectiveFrom:new Date("2026-06-01T00:00:00Z"),effectiveTo:new Date("2026-12-01T00:00:00Z")},NOW_DATE),EffectivePolicyConflictError);}finally{await d.close();}});
