import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import test from "node:test";
import { openScriptDatabase } from "../../scripts/lib/database.mjs";
import { applyMigrationsThrough } from "../helpers/migration-ceiling.mjs";

const runtime=process.env.HSE_QUESTION_BANK_RUNTIME_DIST;assert.ok(runtime,"HSE_QUESTION_BANK_RUNTIME_DIST is required");
const domain=await import(pathToFileURL(join(runtime,"question-bank","question-bank-domain.js")).href);
const serviceModule=await import(pathToFileURL(join(runtime,"question-bank","question-bank-service.js")).href);
const deliveryModule=await import(pathToFileURL(join(runtime,"question-bank","question-delivery-service.js")).href);
const {QuestionBankInputError,QuestionBankAccessError,QuestionBankConflictError}=domain;
const {QuestionBankService}=serviceModule;
const {QuestionDeliveryService}=deliveryModule;
const NOW_DATE=new Date("2026-08-18T02:10:00.000Z"),NOW=NOW_DATE.toISOString(),FUTURE="2099-01-01T00:00:00.000Z";
const ENV={appEnvironment:"test",databaseDriver:"pglite",databaseUrl:null,pgliteDataDir:"memory://",releaseSha:"m2-04-question-bank-runtime",sessionSecret:"m2-04-session-secret-with-more-than-thirty-two-characters",authPepper:"m2-04-auth-pepper-with-more-than-thirty-two-characters",authSandboxEnabled:false,authSandboxAccessKey:null,demoAuthEnabled:false,demoDataEnabled:false};
const oid=(prefix,c)=>`${prefix}_${c.repeat(24)}`;
async function db(){const d=await openScriptDatabase(ENV);await applyMigrationsThrough(d,ENV.releaseSha,"0036_question_bank");return d;}
async function seedAdmin(database,c,{revoked=false}={}){const accountId=`account_m204_admin_${c}`,sessionId=`session_m204_admin_${c}`,email=`admin-m204-${c.toLowerCase()}@example.com`;await database.query(`INSERT INTO auth_accounts(account_id,email_normalized,display_name,account_status,password_hash,email_verified_at,password_set_at,created_at,updated_at) VALUES($1,$2,$3,'active',$4,$5,$5,$5,$5)`,[accountId,email,`Admin ${c}`,"scrypt$16384$8$1$salt$hash",NOW]);await database.query(`INSERT INTO auth_account_roles(account_id,role,created_at) VALUES($1,'admin',$2)`,[accountId,NOW]);await database.query(`INSERT INTO auth_sessions(session_id,account_id,active_role,token_hash,csrf_token_hash,created_at,last_seen_at,expires_at,revoked_at,revocation_reason) VALUES($1,$2,'admin',$3,$4,$5,$5,$6,$7,$8)`,[sessionId,accountId,`token-${c}`,`csrf-${c}`,NOW,FUTURE,revoked?NOW:null,revoked?"runtime_fixture_revoked":null]);return Object.freeze({accountId,sessionId,activeRole:"admin",accountStatus:"active",email,displayName:`Admin ${c}`,createdAt:NOW,lastSeenAt:NOW,expiresAt:FUTURE,tenantMembership:null,authorizedPlatformPermission:"platform.operations.manage"});}
async function seedFramework(database,c){const id=oid("framework",c);await database.query(`INSERT INTO assurance_frameworks(framework_id,framework_reference,title,created_by_account_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$5)`,[id,`FRAME-${c}`,`Framework ${c}`,`account_seed_${c}`,NOW]);return{frameworkId:id,frameworkReference:`FRAME-${c}`};}
const common=(frameworkReference,prompt,questionType,extra={})=>({questionType,prompt,frameworkReference,domainReference:"General Safety",difficulty:"MEDIUM",tags:["safety","core"],...extra});
const rubric={maxScore:10,criteria:[{description:"Identifies the primary hazard",points:4},{description:"Explains the correct control measures",points:6}]};

test("M2.04 accepts all six canonical types and stores immutable current versions",async()=>{const d=await db();try{const admin=await seedAdmin(d,"A"),f=await seedFramework(d,"A"),service=new QuestionBankService(d);const inputs=[
 ["Q-MCQ","MULTIPLE_CHOICE",{options:["Stop work","Continue work","Ignore the hazard"],answerKey:"Stop work"}],
 ["Q-TF","TRUE_FALSE",{answerKey:true}],
 ["Q-SHORT","SHORT_TEXT",{rubric}],
 ["Q-LONG","LONG_TEXT",{rubric}],
 ["Q-INT","INTEGER",{answerKey:5}],
 ["Q-DEC","DECIMAL",{answerKey:2.5}]
 ];for(const [ref,type,extra] of inputs){const made=await service.createQuestion(admin,{questionReference:ref,version:common(f.frameworkReference,`Unique ${type} safety question prompt for runtime validation`,type,extra)},NOW_DATE);assert.equal(made.question.questionStatus,"ACTIVE");assert.equal(made.version.questionType,type);assert.equal(made.version.versionNo,1);}const count=await d.query(`SELECT COUNT(*)::int AS count FROM assessment_questions WHERE question_status='ACTIVE'`);assert.equal(count.rows[0].count,6);}finally{await d.close();}});

test("M2.04 rejects malformed MCQ, boolean, numeric and written question shapes",async()=>{const d=await db();try{const admin=await seedAdmin(d,"B"),f=await seedFramework(d,"B"),service=new QuestionBankService(d);const invalid=[
 common(f.frameworkReference,"Invalid MCQ answer shape prompt","MULTIPLE_CHOICE",{options:["A","A"],answerKey:"A"}),
 common(f.frameworkReference,"Invalid true false answer shape prompt","TRUE_FALSE",{answerKey:"true"}),
 common(f.frameworkReference,"Invalid integer answer shape prompt","INTEGER",{answerKey:2.4}),
 common(f.frameworkReference,"Invalid decimal answer shape prompt","DECIMAL",{answerKey:Number.POSITIVE_INFINITY}),
 common(f.frameworkReference,"Invalid short written rubric prompt","SHORT_TEXT",{rubric:null}),
 common(f.frameworkReference,"Invalid long written rubric totals prompt","LONG_TEXT",{rubric:{maxScore:10,criteria:[{description:"One criterion",points:4}]}})
 ];for(let i=0;i<invalid.length;i++)await assert.rejects(service.createQuestion(admin,{questionReference:`BAD-${i}`,version:invalid[i]},NOW_DATE),QuestionBankInputError);}finally{await d.close();}});

test("M2.04 rejects duplicate active semantic content even under a different reference or option order",async()=>{const d=await db();try{const admin=await seedAdmin(d,"C"),f=await seedFramework(d,"C"),service=new QuestionBankService(d);const first=common(f.frameworkReference,"Which immediate action is correct after finding an uncontrolled hazard?","MULTIPLE_CHOICE",{options:["Stop work","Notify supervisor","Walk away"],answerKey:"Stop work"});await service.createQuestion(admin,{questionReference:"DUP-1",version:first},NOW_DATE);const duplicate=common(f.frameworkReference,"Which immediate action is correct after finding an uncontrolled hazard?","MULTIPLE_CHOICE",{options:["Walk away","Stop work","Notify supervisor"],answerKey:"Stop work"});await assert.rejects(service.createQuestion(admin,{questionReference:"DUP-2",version:duplicate},NOW_DATE),QuestionBankConflictError);}finally{await d.close();}});

test("M2.04 revoked admin cannot mutate and live admin mutations emit dedicated audit events",async()=>{const d=await db();try{const live=await seedAdmin(d,"D"),revoked=await seedAdmin(d,"E",{revoked:true}),f=await seedFramework(d,"D"),service=new QuestionBankService(d),version=common(f.frameworkReference,"Question used to verify fixed-role live admin authorization","TRUE_FALSE",{answerKey:true});await assert.rejects(service.createQuestion(revoked,{questionReference:"REVOKED",version},NOW_DATE),QuestionBankAccessError);const made=await service.createQuestion(live,{questionReference:"AUDIT",version},NOW_DATE);await service.setStatus(live,made.question.questionId,"INACTIVE",NOW_DATE);const events=await d.query(`SELECT action_key FROM platform_audit_events WHERE target_reference=$1 ORDER BY audit_sequence`,[made.question.questionId]);assert.deepEqual(events.rows.map(r=>r.action_key),["assessment.question.created","assessment.question.status.changed"]);}finally{await d.close();}});

test("M2.04 eight-way stale revision race has exactly one winner and preserves every version row",async()=>{const d=await db();try{const admin=await seedAdmin(d,"F"),f=await seedFramework(d,"F"),service=new QuestionBankService(d);const made=await service.createQuestion(admin,{questionReference:"RACE",version:common(f.frameworkReference,"Original question prompt before concurrent revisions","INTEGER",{answerKey:3})},NOW_DATE);const attempts=await Promise.allSettled(Array.from({length:8},(_,i)=>service.reviseQuestion(admin,{questionId:made.question.questionId,expectedCurrentVersionId:made.question.currentVersionId,version:common(f.frameworkReference,`Concurrent revision number ${i} has a distinct safety prompt`,"INTEGER",{answerKey:i+10})},NOW_DATE)));assert.equal(attempts.filter(x=>x.status==="fulfilled").length,1);assert.equal(attempts.filter(x=>x.status==="rejected").length,7);const rows=await d.query(`SELECT version_no FROM assessment_question_versions WHERE question_id=$1 ORDER BY version_no`,[made.question.questionId]);assert.deepEqual(rows.rows.map(r=>Number(r.version_no)),[1,2]);const audits=await d.query(`SELECT action_key FROM platform_audit_events WHERE target_reference=$1 ORDER BY audit_sequence`,[made.question.questionId]);assert.deepEqual(audits.rows.map(r=>r.action_key),["assessment.question.created","assessment.question.revised"]);}finally{await d.close();}});

test("M2.04 delivery projection exposes no hidden answer or scoring material",async()=>{const d=await db();try{const admin=await seedAdmin(d,"G"),f=await seedFramework(d,"G"),service=new QuestionBankService(d),delivery=new QuestionDeliveryService(d);const made=await service.createQuestion(admin,{questionReference:"DELIVERY",version:common(f.frameworkReference,"Select the safe isolation method before maintenance begins","MULTIPLE_CHOICE",{options:["Lockout tagout","Verbal warning only","No isolation"],answerKey:"Lockout tagout"})},NOW_DATE);const publicVersion=await delivery.findActiveVersion(made.question.currentVersionId);assert.ok(publicVersion);assert.deepEqual(Object.keys(publicVersion).sort(),["difficulty","domainReference","frameworkId","options","prompt","questionId","questionType","questionVersionId","tags"].sort());assert.equal(JSON.stringify(publicVersion).includes("Lockout tagout"),true,"public options remain visible");assert.equal(Object.hasOwn(publicVersion,"answerKey"),false);assert.equal(Object.hasOwn(publicVersion,"rubric"),false);assert.equal(Object.hasOwn(publicVersion,"contentFingerprint"),false);}finally{await d.close();}});

test("M2.04 version history rejects UPDATE and DELETE tampering",async()=>{const d=await db();try{const admin=await seedAdmin(d,"H"),f=await seedFramework(d,"H"),service=new QuestionBankService(d);const made=await service.createQuestion(admin,{questionReference:"IMMUTABLE",version:common(f.frameworkReference,"Immutable question version history must reject direct tampering","TRUE_FALSE",{answerKey:false})},NOW_DATE);await assert.rejects(d.query(`UPDATE assessment_question_versions SET prompt='tampered prompt value' WHERE question_version_id=$1`,[made.question.currentVersionId]),e=>e?.code==="55000");await assert.rejects(d.query(`DELETE FROM assessment_question_versions WHERE question_version_id=$1`,[made.question.currentVersionId]),e=>e?.code==="55000");}finally{await d.close();}});

test("M2.04 history-preserving down/reapply retains questions and versions",async()=>{const d=await db();try{const admin=await seedAdmin(d,"I"),f=await seedFramework(d,"I"),service=new QuestionBankService(d);const made=await service.createQuestion(admin,{questionReference:"RETAIN",version:common(f.frameworkReference,"Question history must remain after a milestone rollback script","DECIMAL",{answerKey:1.25})},NOW_DATE);await d.execute(readFileSync("database/migrations/0036_question_bank.down.sql","utf8"));assert.equal((await d.query(`SELECT COUNT(*)::int AS count FROM assessment_question_versions WHERE question_id=$1`,[made.question.questionId])).rows[0].count,1);await d.execute(readFileSync("database/migrations/0036_question_bank.up.sql","utf8"));assert.equal((await d.query(`SELECT COUNT(*)::int AS count FROM assessment_question_versions WHERE question_id=$1`,[made.question.questionId])).rows[0].count,1);}finally{await d.close();}});
